#!/usr/bin/env bash
# Sourced by install.sh for `--home DIR`: the EXTERNAL layout, for a
# repository that may not hold Claude or pipeline files.
#
# Everything the pipeline owns -- .claude/, CLAUDE.md, the pipeline's docs --
# goes to DIR. The repository gets nothing written to it, not even a
# .gitignore line.
#
# What makes Claude Code load it all from outside the repository (checked
# against code.claude.com/docs, 2026-09):
#
#   --settings DIR/.claude/settings.json   hooks and permissions. A `/path`
#                                          permission rule in a --settings file
#                                          anchors at that file's directory.
#   --add-dir DIR                          skills, agents and commands under
#                                          DIR/.claude/
#   CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD=1
#                                          DIR/CLAUDE.md and DIR/.claude/rules
#
# Plain `claude` in the repository loads NONE of that, so the launcher this
# writes is the only supported way in. That is the failure the field report
# described: files moved somewhere Claude Code does not look, followed only
# while somebody kept pointing at them.

# ext_native <dir> -- the spelling a native Windows program (claude.exe) and
# Git Bash both accept: C:/Users/x on Windows, the path itself elsewhere.
ext_native() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m -l "$1"; else printf '%s' "$1"; fi
}

# ext_check_disjoint <home> <project> -- refuse a home inside the project (the
# repository must hold none of it) or a project inside the home (the gate finds
# the NEAREST gate.json walking up, so the home's would claim every source
# path, strip it relative to the wrong directory, and match no root).
ext_check_disjoint() {
  local h p
  h="$(cd "$1" && pwd -P)"; p="$(cd "$2" && pwd -P)"
  h="${h,,}"; p="${p,,}"
  case "$h/" in "$p"/*) die "--home $1 is inside the project. It must live outside the repository." ;; esac
  case "$p/" in "$h"/*) die "the project is inside --home $1. Put the home beside the repository, not around it." ;; esac
}

# _ext_sed_repl <value> -- escape for a sed replacement using # as delimiter.
# `#`, not `|`: the patterns below use `|` for alternation.
_ext_sed_repl() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/&/\\&/g' -e 's/#/\\#/g'; }

# ext_rewrite_settings <settings.json> <home> -- hook commands become absolute
# and run through bash explicitly (on Windows there is no executable bit to
# rely on); enforcement-file deny rules re-anchor at the settings file's own
# directory, which is <home>/.claude.
ext_rewrite_settings() {
  local f="$1" h
  h="$(_ext_sed_repl "$(printf '%s' "$2" | sed 's/"/\\"/g')")"
  sed -E -i \
    -e "s#\"command\": \"\\.claude/hooks/([A-Za-z0-9_.-]+\\.sh)([^\"]*)\"#\"command\": \"bash \\\\\"$h/.claude/hooks/\\1\\\\\"\\2\"#g" \
    -e 's#(Write|Edit|Read)\(\./\.claude/#\1(/#g' \
    "$f"
}

# ext_rewrite_docs <home> <file>... -- the pipeline's own paths in skills,
# agents, rules and CLAUDE.md point into the home. Done here, deterministically,
# rather than by telling the model "docs/specs means somewhere else": a
# translation the model has to remember is the drift this layout was reported
# for. Project documentation (docs/architecture.md, docs/api) stays in the
# repository and is left alone.
ext_rewrite_docs() {
  local home="$1" h q=""; shift
  case "$home" in *" "*) q='"' ;; esac
  h="$(_ext_sed_repl "$home")"
  local pre='(^|[^A-Za-z0-9_./~-])'
  local tail='([A-Za-z0-9_.*<>{}/-]*)'
  [ $# -gt 0 ] || return 0
  sed -E -i \
    -e "s#${pre}\\.claude/(scripts|state|hooks)/${tail}#\\1${q}${h}/.claude/\\2/\\3${q}#g" \
    -e "s#${pre}docs/(specs|reports|adr|handoff|setup)(/${tail})?#\\1${q}${h}/docs/\\2\\3${q}#g" \
    "$@"
}

# ext_write_launchers <home> <project> -- iptcvd-claude (bash),
# iptcvd-claude.ps1 and iptcvd-claude.cmd (Windows), all in the home.
ext_write_launchers() {
  local home="$1" proj="$2" ps_home ps_proj
  {
    echo '#!/usr/bin/env bash'
    echo '# Generated by IPTCVD Pipeline (install.sh --home). Starts Claude Code on the'
    echo '# project with the pipeline loaded from this home. Plain `claude` in the'
    echo '# project loads none of it: no hooks, no skills, no gate.'
    printf 'cd %q || exit 1\n' "$proj"
    echo 'export CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD=1'
    printf 'exec claude --settings %q --add-dir %q "$@"\n' "$home/.claude/settings.json" "$home"
  } > "$home/iptcvd-claude"
  chmod +x "$home/iptcvd-claude" 2>/dev/null || true

  ps_home="${home//\'/\'\'}"; ps_proj="${proj//\'/\'\'}"
  {
    echo '# Generated by IPTCVD Pipeline (install.sh --home). Starts Claude Code on the'
    echo '# project with the pipeline loaded from this home. Plain `claude` in the'
    echo '# project loads none of it: no hooks, no skills, no gate.'
    echo '$env:CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD = "1"'
    printf "Set-Location -LiteralPath '%s'\n" "$ps_proj"
    printf "& claude --settings '%s/.claude/settings.json' --add-dir '%s' @args\n" "$ps_home" "$ps_home"
    echo 'exit $LASTEXITCODE'
  } > "$home/iptcvd-claude.ps1"

  printf '@echo off\r\npowershell -NoProfile -ExecutionPolicy Bypass -File "%%~dp0iptcvd-claude.ps1" %%*\r\n' \
    > "$home/iptcvd-claude.cmd"
}
